{% set version = "0.25.8" %}

package:
  name: pycraf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycraf/pycraf-{{ version }}.tar.gz
  sha256: ed3f2a5f1d9492b9dda2634a41341c133e09965d2ef09017b4cd6e98d738a33a

build:
  number: 1
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - openmp 4.0.*  # [osx]
    - numpy
    - cython
    - astropy >=2.0.11
    - scipy
  run:
    - python
    - openmp 4.0.*  # [osx]
    - astropy >=2.0.11
    - {{ pin_compatible('numpy') }}
    - scipy
    - h5py
    - matplotlib-base >=2.0
    - pyproj

test:
  imports:
    - pycraf
    - pycraf.conversions
    - pycraf.atm
    - pycraf.pathprof
    - pycraf.antenna
    - pycraf.protection
    - pycraf.geospatial
    - pycraf.satellite
    - pycraf.geometry
    - pycraf.mc
    - pycraf.utils

  commands:
     python -c "import pycraf; pycraf.test()"

about:
  home: https://github.com/bwinkel/pycraf
  license: GPL-3.0
  license_family: GPL
  license_file: licenses/README.rst
  summary: 'A Python package for spectrum-management compatibility studies'
  description: |
      The pycraf package provides functions and procedures for various tasks in spectrum-management compatibility studies.
  dev_url: https://github.com/bwinkel/pycraf

extra:
  recipe-maintainers:
    - bwinkel
