{% set name = "pycraf" %}
{% set version = "1.1.1" %}
{% set sha256 = "cdf5c2564ecea07e3242f5422a64ccc31a6a4d80f070ecc2d3abc804f8b737c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py27 or (osx and py>=38)]
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt --offline

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - openmp 4.0.*  # [osx]
    - python
    - pip
    - setuptools
    - astropy
    - cython
    - numpy
    - scipy

  run:
    - python
    - openmp 4.0.*  # [osx]
    - astropy
    - {{ pin_compatible('numpy') }}
    - scipy
    - h5py
    - matplotlib >=2.0
    - pyproj <3.0
    - pyqt
    - pytest
    - pytest-astropy
    - pytest-doctestplus
    - pytest-qt
    - sgp4

test:
  imports:
    - pycraf
    - pycraf.conversions
    - pycraf.atm
    - pycraf.pathprof
    - pycraf.antenna
    - pycraf.protection
    - pycraf.geospatial
    - pycraf.satellite
    - pycraf.geometry
    - pycraf.mc
    - pycraf.utils

  commands: python -c "import pycraf; pycraf.test()"

about:
  home: https://github.com/bwinkel/pycraf
  license: GPL-3.0
  license_family: GPL
  license_file: licenses/README.rst
  summary: A Python package for spectrum-management compatibility studies
  description: |
    The pycraf package provides functions and procedures for various tasks in spectrum-management compatibility studies.
  dev_url: https://github.com/bwinkel/pycraf

extra:
  recipe-maintainers:
    - bwinkel
